export const ROUTE = {
  ABOUT_US: '/about-us',
  ADMIN: '/admin',
  CONTACT_FORM: '/contact-form',
  CONTACT_REQUESTS: '/contact-requests',
  DOCS: '/docs',
  INFO: '/info',
  HOME: '/',
  LOGOUT: '/logout',
  PRICE: '/price',
  PROFILE: '/profile',
  RSS_FEED_DETAIL: '/rss-feed/:id',
  RSS_FEED_LIST: '/rss-feed/list',
  SETTINGS: '/settings',
  TICKETS: '/ticket/list',
  TICKET: '/ticket/form/:_id',
};
