export const ROUTE = {
  ABOUT_US: '/about-us',
  ADMIN: '/admin',
  CONTACT_FORM: '/contact-form',
  DOCS: '/docs',
  FAQS: '/faqs',
  INFO: '/info',
  HELP: '/help',
  HOME: '/',
  LOGOUT: '/logout',
  PRICE: '/price',
  PROFILE: '/profile',
  RESET_PASSWORD: '/reset-password/:_id',
  RSS_FEED_DETAIL: '/rss-feed/:_id',
  RSS_FEED_LIST: '/rss-feed/list',
  SETTINGS: '/settings',
  SETTINGS_ABOUT_US: '/settings/about-us',
  SETTINGS_CONTACT_REQUESTS_LIST: '/settings/contact-requests',
  SETTINGS_FAQS_LIST: '/settings/faqs',
  SETTINGS_FAQS_FORM: '/settings/faqs/form/:_id',
  SETTINGS_TICKETS_LIST: '/settings/tickets',
  SETTINGS_TICKETS_FORM: '/settings/tickets/form/:_id',
  STORES: '/stores',
  TICKETS_FORM: '/tickets/form/:_id',
  USER_PROFILES: '/user-profiles',
  WALLET: '/wallet'
};
