export const ROUTE = {
  ABOUT_US: '/about-us',
  ADMIN: '/admin',
  CONTACT_FORM: '/contact-form',
  CONTACT_REQUESTS: '/contact-requests',
  DOCS: '/docs',
  FAQS: '/faqs',
  INFO: '/info',
  HELP: '/help',
  HOME: '/',
  LOGOUT: '/logout',
  PRICE: '/price',
  PROFILE: '/profile',
  RESET_PASSWORD: '/reset-password/:id',
  RSS_FEED_DETAIL: '/rss-feed/:id',
  RSS_FEED_LIST: '/rss-feed/list',
  SETTINGS: '/settings',
  STORES: '/stores',
  TICKETS: '/ticket/list',
  TICKET: '/ticket/form/:id',
  USER_PROFILES: '/user-profiles',
  WALLET: '/wallet'
};
